In [1]:
import numpy as np

In [3]:
#Create a numpy array
x=np.array([1,2,3,4])

In [4]:
type(x)

numpy.ndarray

In [5]:
my_matrix=[[1,2,3],[4,5,6],[6,7,8]]

In [6]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [6, 7, 8]])

In [8]:
list(range(0,5))

[0, 1, 2, 3, 4]

In [10]:
np.arange(0,20,5)

array([ 0,  5, 10, 15])

In [11]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [12]:
type(1)

int

In [13]:
type(1.0)

float

In [14]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [15]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [17]:
np.linspace(0,10,30)

array([ 0.        ,  0.34482759,  0.68965517,  1.03448276,  1.37931034,
        1.72413793,  2.06896552,  2.4137931 ,  2.75862069,  3.10344828,
        3.44827586,  3.79310345,  4.13793103,  4.48275862,  4.82758621,
        5.17241379,  5.51724138,  5.86206897,  6.20689655,  6.55172414,
        6.89655172,  7.24137931,  7.5862069 ,  7.93103448,  8.27586207,
        8.62068966,  8.96551724,  9.31034483,  9.65517241, 10.        ])

In [18]:
np.eye(4)#Identity matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [20]:
np.random.rand(1) #returns random number between 0 and 1

array([0.5996795])

In [21]:
np.random.rand(5,4) #returns matrix of 5 by 4 having values betwen 0 and 1 #uniform distribution

array([[0.09561732, 0.51838623, 0.03042339, 0.35337892],
       [0.05650491, 0.02896382, 0.57287692, 0.32213975],
       [0.61933566, 0.17267852, 0.75318111, 0.53119969],
       [0.72114773, 0.7038122 , 0.44252436, 0.61229367],
       [0.12522882, 0.80888394, 0.67253744, 0.37169271]])

In [23]:
#normal distribution
np.random.randn(5,4)

array([[ 1.70157428,  0.74082357, -1.5586785 ,  0.37929954],
       [-1.18429531,  0.55958128, -1.23433407,  0.42616539],
       [ 1.02042813, -1.41091482, -0.14671159,  1.3764454 ],
       [ 0.57493298,  0.5849383 , -0.12778327,  0.22857701],
       [ 1.63944318, -0.06763607,  0.59350558, -1.02145116]])

In [26]:
np.random.randint(1,100,5)

array([12, 79, 10, 12, 66])

In [27]:
arr=np.arange(25)
rarr=np.random.randint(0,50,10)

In [28]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [29]:
rarr

array([ 6, 16, 28, 20, 19, 13, 15, 37,  6,  0])

In [30]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [31]:
arr.shape

(25,)

In [32]:
arr.reshape(5,5).shape

(5, 5)

In [33]:
arr.dtype

dtype('int32')

In [34]:
rarr.max()

37

In [35]:
rarr.argmax() #index of the maximum value #same with minimum

7

In [36]:
arr=np.arange(0,10)

In [37]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
arr+arr # addition based on index

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [39]:
arr*arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [40]:
arr/arr

C:\Users\nNaaz\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [41]:
1/arr

C:\Users\nNaaz\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [42]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [43]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [44]:
np.max(arr)

9

In [45]:
arr.max()

9

In [46]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [47]:
arr[8]#returns value at index 8

8

In [48]:
arr[1:5]

array([1, 2, 3, 4])

In [49]:
arr[3:]

array([3, 4, 5, 6, 7, 8, 9])

In [50]:
#Broadcasting #this u cant do in normla list
arr[0:5]=100
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9])

In [55]:
slice_of_arr=arr[5:]

In [56]:
slice_of_arr

array([5, 6, 7, 8, 9])

In [57]:
slice_of_arr [:]=99

In [58]:
slice_of_arr

array([99, 99, 99, 99, 99])

In [59]:
arr

array([100, 100, 100, 100, 100,  99,  99,  99,  99,  99])

In [60]:
arr_copy=arr.copy()

In [61]:
arr_copy[:]=88

In [62]:
arr_copy

array([88, 88, 88, 88, 88, 88, 88, 88, 88, 88])

In [63]:
arr

array([100, 100, 100, 100, 100,  99,  99,  99,  99,  99])

In [64]:
#mat[row,col]
#mat[row],[col]
mat = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [65]:
mat

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [66]:
mat[0]

array([ 5, 10, 15])

In [67]:
mat[2]

array([35, 40, 45])

In [68]:
#grab 25
mat[1][1] #OR mat[1,1]

25

In [70]:
#slicing from matrix
mat[:2,1:]

array([[10, 15],
       [25, 30]])

In [71]:
mat[1:,:2]

array([[20, 25],
       [35, 40]])

In [72]:
#conditional Selection
arr=np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [74]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [75]:
bool_arr=arr>4

In [76]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [77]:
arr[arr>4]

array([ 5,  6,  7,  8,  9, 10])